/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalvicieRouteImport } from './routes/calvicie'
import { Route as DiagnosticoCapilarRouteImport } from './routes/diagnostico-capilar'
import { Route as EspessuraFiosRouteImport } from './routes/espessura-fios'
import { Route as MotivacionalRouteImport } from './routes/motivacional'
import { Route as NomeRouteImport } from './routes/nome'
import { Route as RegiaoQuedaRouteImport } from './routes/regiao-queda'
import { Route as TempoQuedaRouteImport } from './routes/tempo-queda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalvicieRoute = CalvicieRouteImport.update({
  id: '/calvicie',
  path: '/calvicie',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoCapilarRoute = DiagnosticoCapilarRouteImport.update({
  id: '/diagnostico-capilar',
  path: '/diagnostico-capilar',
  getParentRoute: () => rootRouteImport,
} as any)
const EspessuraFiosRoute = EspessuraFiosRouteImport.update({
  id: '/espessura-fios',
  path: '/espessura-fios',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivacionalRoute = MotivacionalRouteImport.update({
  id: '/motivacional',
  path: '/motivacional',
  getParentRoute: () => rootRouteImport,
} as any)
const NomeRoute = NomeRouteImport.update({
  id: '/nome',
  path: '/nome',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiaoQuedaRoute = RegiaoQuedaRouteImport.update({
  id: '/regiao-queda',
  path: '/regiao-queda',
  getParentRoute: () => rootRouteImport,
} as any)
const TempoQuedaRoute = TempoQuedaRouteImport.update({
  id: '/tempo-queda',
  path: '/tempo-queda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/diagnostico-capilar': typeof DiagnosticoCapilarRoute
  '/espessura-fios': typeof EspessuraFiosRoute
  '/motivacional': typeof MotivacionalRoute
  '/nome': typeof NomeRoute
  '/regiao-queda': typeof RegiaoQuedaRoute
  '/tempo-queda': typeof TempoQuedaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/diagnostico-capilar': typeof DiagnosticoCapilarRoute
  '/espessura-fios': typeof EspessuraFiosRoute
  '/motivacional': typeof MotivacionalRoute
  '/nome': typeof NomeRoute
  '/regiao-queda': typeof RegiaoQuedaRoute
  '/tempo-queda': typeof TempoQuedaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/diagnostico-capilar': typeof DiagnosticoCapilarRoute
  '/espessura-fios': typeof EspessuraFiosRoute
  '/motivacional': typeof MotivacionalRoute
  '/nome': typeof NomeRoute
  '/regiao-queda': typeof RegiaoQuedaRoute
  '/tempo-queda': typeof TempoQuedaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calvicie'
    | '/diagnostico-capilar'
    | '/espessura-fios'
    | '/motivacional'
    | '/nome'
    | '/regiao-queda'
    | '/tempo-queda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calvicie'
    | '/diagnostico-capilar'
    | '/espessura-fios'
    | '/motivacional'
    | '/nome'
    | '/regiao-queda'
    | '/tempo-queda'
  id:
    | '__root__'
    | '/'
    | '/calvicie'
    | '/diagnostico-capilar'
    | '/espessura-fios'
    | '/motivacional'
    | '/nome'
    | '/regiao-queda'
    | '/tempo-queda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalvicieRoute: typeof CalvicieRoute
  DiagnosticoCapilarRoute: typeof DiagnosticoCapilarRoute
  EspessuraFiosRoute: typeof EspessuraFiosRoute
  MotivacionalRoute: typeof MotivacionalRoute
  NomeRoute: typeof NomeRoute
  RegiaoQuedaRoute: typeof RegiaoQuedaRoute
  TempoQuedaRoute: typeof TempoQuedaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calvicie': {
      id: '/calvicie'
      path: '/calvicie'
      fullPath: '/calvicie'
      preLoaderRoute: typeof CalvicieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-capilar': {
      id: '/diagnostico-capilar'
      path: '/diagnostico-capilar'
      fullPath: '/diagnostico-capilar'
      preLoaderRoute: typeof DiagnosticoCapilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espessura-fios': {
      id: '/espessura-fios'
      path: '/espessura-fios'
      fullPath: '/espessura-fios'
      preLoaderRoute: typeof EspessuraFiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivacional': {
      id: '/motivacional'
      path: '/motivacional'
      fullPath: '/motivacional'
      preLoaderRoute: typeof MotivacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nome': {
      id: '/nome'
      path: '/nome'
      fullPath: '/nome'
      preLoaderRoute: typeof NomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regiao-queda': {
      id: '/regiao-queda'
      path: '/regiao-queda'
      fullPath: '/regiao-queda'
      preLoaderRoute: typeof RegiaoQuedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempo-queda': {
      id: '/tempo-queda'
      path: '/tempo-queda'
      fullPath: '/tempo-queda'
      preLoaderRoute: typeof TempoQuedaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalvicieRoute: CalvicieRoute,
  DiagnosticoCapilarRoute: DiagnosticoCapilarRoute,
  EspessuraFiosRoute: EspessuraFiosRoute,
  MotivacionalRoute: MotivacionalRoute,
  NomeRoute: NomeRoute,
  RegiaoQuedaRoute: RegiaoQuedaRoute,
  TempoQuedaRoute: TempoQuedaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
