/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalvicieRouteImport } from './routes/calvicie'
import { Route as CouroCabeludoRouteImport } from './routes/couro-cabeludo'
import { Route as DiagnosticoCapilarRouteImport } from './routes/diagnostico-capilar'
import { Route as EspessuraFiosRouteImport } from './routes/espessura-fios'
import { Route as FrequenciaCuidadosRouteImport } from './routes/frequencia-cuidados'
import { Route as MotivacionalRouteImport } from './routes/motivacional'
import { Route as NomeRouteImport } from './routes/nome'
import { Route as PeriodoAfinamentoRouteImport } from './routes/periodo-afinamento'
import { Route as RegiaoQuedaRouteImport } from './routes/regiao-queda'
import { Route as TempoQuedaRouteImport } from './routes/tempo-queda'
import { Route as TratamentoAnteriorRouteImport } from './routes/tratamento-anterior'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalvicieRoute = CalvicieRouteImport.update({
  id: '/calvicie',
  path: '/calvicie',
  getParentRoute: () => rootRouteImport,
} as any)
const CouroCabeludoRoute = CouroCabeludoRouteImport.update({
  id: '/couro-cabeludo',
  path: '/couro-cabeludo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoCapilarRoute = DiagnosticoCapilarRouteImport.update({
  id: '/diagnostico-capilar',
  path: '/diagnostico-capilar',
  getParentRoute: () => rootRouteImport,
} as any)
const EspessuraFiosRoute = EspessuraFiosRouteImport.update({
  id: '/espessura-fios',
  path: '/espessura-fios',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequenciaCuidadosRoute = FrequenciaCuidadosRouteImport.update({
  id: '/frequencia-cuidados',
  path: '/frequencia-cuidados',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivacionalRoute = MotivacionalRouteImport.update({
  id: '/motivacional',
  path: '/motivacional',
  getParentRoute: () => rootRouteImport,
} as any)
const NomeRoute = NomeRouteImport.update({
  id: '/nome',
  path: '/nome',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodoAfinamentoRoute = PeriodoAfinamentoRouteImport.update({
  id: '/periodo-afinamento',
  path: '/periodo-afinamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiaoQuedaRoute = RegiaoQuedaRouteImport.update({
  id: '/regiao-queda',
  path: '/regiao-queda',
  getParentRoute: () => rootRouteImport,
} as any)
const TempoQuedaRoute = TempoQuedaRouteImport.update({
  id: '/tempo-queda',
  path: '/tempo-queda',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentoAnteriorRoute = TratamentoAnteriorRouteImport.update({
  id: '/tratamento-anterior',
  path: '/tratamento-anterior',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/couro-cabeludo': typeof CouroCabeludoRoute
  '/diagnostico-capilar': typeof DiagnosticoCapilarRoute
  '/espessura-fios': typeof EspessuraFiosRoute
  '/frequencia-cuidados': typeof FrequenciaCuidadosRoute
  '/motivacional': typeof MotivacionalRoute
  '/nome': typeof NomeRoute
  '/periodo-afinamento': typeof PeriodoAfinamentoRoute
  '/regiao-queda': typeof RegiaoQuedaRoute
  '/tempo-queda': typeof TempoQuedaRoute
  '/tratamento-anterior': typeof TratamentoAnteriorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/couro-cabeludo': typeof CouroCabeludoRoute
  '/diagnostico-capilar': typeof DiagnosticoCapilarRoute
  '/espessura-fios': typeof EspessuraFiosRoute
  '/frequencia-cuidados': typeof FrequenciaCuidadosRoute
  '/motivacional': typeof MotivacionalRoute
  '/nome': typeof NomeRoute
  '/periodo-afinamento': typeof PeriodoAfinamentoRoute
  '/regiao-queda': typeof RegiaoQuedaRoute
  '/tempo-queda': typeof TempoQuedaRoute
  '/tratamento-anterior': typeof TratamentoAnteriorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/couro-cabeludo': typeof CouroCabeludoRoute
  '/diagnostico-capilar': typeof DiagnosticoCapilarRoute
  '/espessura-fios': typeof EspessuraFiosRoute
  '/frequencia-cuidados': typeof FrequenciaCuidadosRoute
  '/motivacional': typeof MotivacionalRoute
  '/nome': typeof NomeRoute
  '/periodo-afinamento': typeof PeriodoAfinamentoRoute
  '/regiao-queda': typeof RegiaoQuedaRoute
  '/tempo-queda': typeof TempoQuedaRoute
  '/tratamento-anterior': typeof TratamentoAnteriorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calvicie'
    | '/couro-cabeludo'
    | '/diagnostico-capilar'
    | '/espessura-fios'
    | '/frequencia-cuidados'
    | '/motivacional'
    | '/nome'
    | '/periodo-afinamento'
    | '/regiao-queda'
    | '/tempo-queda'
    | '/tratamento-anterior'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calvicie'
    | '/couro-cabeludo'
    | '/diagnostico-capilar'
    | '/espessura-fios'
    | '/frequencia-cuidados'
    | '/motivacional'
    | '/nome'
    | '/periodo-afinamento'
    | '/regiao-queda'
    | '/tempo-queda'
    | '/tratamento-anterior'
  id:
    | '__root__'
    | '/'
    | '/calvicie'
    | '/couro-cabeludo'
    | '/diagnostico-capilar'
    | '/espessura-fios'
    | '/frequencia-cuidados'
    | '/motivacional'
    | '/nome'
    | '/periodo-afinamento'
    | '/regiao-queda'
    | '/tempo-queda'
    | '/tratamento-anterior'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalvicieRoute: typeof CalvicieRoute
  CouroCabeludoRoute: typeof CouroCabeludoRoute
  DiagnosticoCapilarRoute: typeof DiagnosticoCapilarRoute
  EspessuraFiosRoute: typeof EspessuraFiosRoute
  FrequenciaCuidadosRoute: typeof FrequenciaCuidadosRoute
  MotivacionalRoute: typeof MotivacionalRoute
  NomeRoute: typeof NomeRoute
  PeriodoAfinamentoRoute: typeof PeriodoAfinamentoRoute
  RegiaoQuedaRoute: typeof RegiaoQuedaRoute
  TempoQuedaRoute: typeof TempoQuedaRoute
  TratamentoAnteriorRoute: typeof TratamentoAnteriorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calvicie': {
      id: '/calvicie'
      path: '/calvicie'
      fullPath: '/calvicie'
      preLoaderRoute: typeof CalvicieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couro-cabeludo': {
      id: '/couro-cabeludo'
      path: '/couro-cabeludo'
      fullPath: '/couro-cabeludo'
      preLoaderRoute: typeof CouroCabeludoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-capilar': {
      id: '/diagnostico-capilar'
      path: '/diagnostico-capilar'
      fullPath: '/diagnostico-capilar'
      preLoaderRoute: typeof DiagnosticoCapilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espessura-fios': {
      id: '/espessura-fios'
      path: '/espessura-fios'
      fullPath: '/espessura-fios'
      preLoaderRoute: typeof EspessuraFiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequencia-cuidados': {
      id: '/frequencia-cuidados'
      path: '/frequencia-cuidados'
      fullPath: '/frequencia-cuidados'
      preLoaderRoute: typeof FrequenciaCuidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivacional': {
      id: '/motivacional'
      path: '/motivacional'
      fullPath: '/motivacional'
      preLoaderRoute: typeof MotivacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nome': {
      id: '/nome'
      path: '/nome'
      fullPath: '/nome'
      preLoaderRoute: typeof NomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodo-afinamento': {
      id: '/periodo-afinamento'
      path: '/periodo-afinamento'
      fullPath: '/periodo-afinamento'
      preLoaderRoute: typeof PeriodoAfinamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regiao-queda': {
      id: '/regiao-queda'
      path: '/regiao-queda'
      fullPath: '/regiao-queda'
      preLoaderRoute: typeof RegiaoQuedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempo-queda': {
      id: '/tempo-queda'
      path: '/tempo-queda'
      fullPath: '/tempo-queda'
      preLoaderRoute: typeof TempoQuedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamento-anterior': {
      id: '/tratamento-anterior'
      path: '/tratamento-anterior'
      fullPath: '/tratamento-anterior'
      preLoaderRoute: typeof TratamentoAnteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalvicieRoute: CalvicieRoute,
  CouroCabeludoRoute: CouroCabeludoRoute,
  DiagnosticoCapilarRoute: DiagnosticoCapilarRoute,
  EspessuraFiosRoute: EspessuraFiosRoute,
  FrequenciaCuidadosRoute: FrequenciaCuidadosRoute,
  MotivacionalRoute: MotivacionalRoute,
  NomeRoute: NomeRoute,
  PeriodoAfinamentoRoute: PeriodoAfinamentoRoute,
  RegiaoQuedaRoute: RegiaoQuedaRoute,
  TempoQuedaRoute: TempoQuedaRoute,
  TratamentoAnteriorRoute: TratamentoAnteriorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
