/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalvicieRouteImport } from './routes/calvicie'
import { Route as NomeRouteImport } from './routes/nome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalvicieRoute = CalvicieRouteImport.update({
  id: '/calvicie',
  path: '/calvicie',
  getParentRoute: () => rootRouteImport,
} as any)
const NomeRoute = NomeRouteImport.update({
  id: '/nome',
  path: '/nome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/nome': typeof NomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/nome': typeof NomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calvicie': typeof CalvicieRoute
  '/nome': typeof NomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calvicie' | '/nome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calvicie' | '/nome'
  id: '__root__' | '/' | '/calvicie' | '/nome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalvicieRoute: typeof CalvicieRoute
  NomeRoute: typeof NomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calvicie': {
      id: '/calvicie'
      path: '/calvicie'
      fullPath: '/calvicie'
      preLoaderRoute: typeof CalvicieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nome': {
      id: '/nome'
      path: '/nome'
      fullPath: '/nome'
      preLoaderRoute: typeof NomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalvicieRoute: CalvicieRoute,
  NomeRoute: NomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
